### ISSUE TITLE
AbstractMethodError with IPlayerEventListener added to a SimpleExoPlayer

### ISSUE THREAD

**Issue by kcrg** [Baseflow/ExoPlayerXamarin#112]
## 🔙 Regression
In the latest version of ExoPlayer, the IPlayerEventListener interface causes a crash.

### Old (and correct) behavior
App with version 2.8.8 works just fine.

### Current behavior
Player crashes with this stack trace:

> java.lang.AbstractMethodError: abstract method "void com.google.android.exoplayer2.Player$EventListener.onTimelineChanged(com.google.android.exoplayer2.Timeline, int)"
	at crc64c7906c01a42d8080.DroidEventLogger.n_onTimelineChanged(Native Method)
	at crc64c7906c01a42d8080.DroidEventLogger.onTimelineChanged(DroidEventLogger.java:162)
	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.lambda$run$0$ExoPlayerImpl$PlaybackInfoUpdate(ExoPlayerImpl.java:804)
	at com.google.android.exoplayer2.-$$Lambda$ExoPlayerImpl$PlaybackInfoUpdate$N_S5kRfhaRTAkH28P5luFgKnFjQ.invokeListener(Unknown Source:2)
	at com.google.android.exoplayer2.BasePlayer$ListenerHolder.invoke(BasePlayer.java:182)
	at com.google.android.exoplayer2.ExoPlayerImpl.invokeAll(ExoPlayerImpl.java:845)
	at com.google.android.exoplayer2.ExoPlayerImpl.access$000(ExoPlayerImpl.java:43)
	at com.google.android.exoplayer2.ExoPlayerImpl$PlaybackInfoUpdate.run(ExoPlayerImpl.java:802)
	at com.google.android.exoplayer2.ExoPlayerImpl.notifyListeners(ExoPlayerImpl.java:736)
	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(ExoPlayerImpl.java:710)
	at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(ExoPlayerImpl.java:652)
	at com.google.android.exoplayer2.ExoPlayerImpl.handleEvent(ExoPlayerImpl.java:595)
	at com.google.android.exoplayer2.ExoPlayerImpl$1.handleMessage(ExoPlayerImpl.java:127)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

This applies to any version 2.11.x.

### Reproduction steps
Add IPlayerEventListener to player logic.

### Configuration

**Version:** 2.11.x
**Debug config:** D8 and AAPT2
**Release config:** D8 and R8
Android target version is set to API30

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

### Workaround(?)
Set minimum Android version to around API 28

**Comment by cncb-gh** [comment]
Still an issue in 2.11.8

**Comment by kcrg** [comment]
> Still an issue in 2.11.8

That's why I created this issue 😅

**Comment by billel-bouziani** [comment]
Happened to me, but I have figured how to fix it
it seems that the definition of IPlayerEventListener interface has been changed (names and definitions of methods have been changed ).from 2.8.8 to the 2.9.x

eg:

OnTimelineChanged(Timeline p0, Java.Lang.Object p1, int p2) to 
OnTimelineChanged(Timeline timeline, int reason)

**Comment by cncb-gh** [comment]
> 
> eg:
> 
> OnTimelineChanged(Timeline p0, Java.Lang.Object p1, int p2) to
> OnTimelineChanged(Timeline timeline, int reason)

This plus adding a missing OnIsPlayingChanged(bool isPlaying) also fixed it for me.  Thanks!  Kind of puzzling that this builds successfully before doing this.

**Comment by ScriptSun** [comment]
@billel-bouziani can you share your code and how you fixed I am facing now the same issue on version 2.18.3 the function add listener is not working at all
